---
title: "Sensor Data MPI Test 1.2"
author: "Heike Sprenger"
date: "Monday, June 01, 2015"
output: html_document
---


```{r setup}
library(knitr)
opts_knit$set(root.dir = '../')
```


### Set working directory  
```{r set working directory}
#getwd()
#setwd("D:/work/repos/trost_phenotypes")
```


[solution for issue with working directory and knitr](https://github.com/yihui/knitr/issues/277)

### Load workspace, packages and scripts
```{r load workspace, message=FALSE}
# load packages
library(ggplot2)
library(reshape)
library(pander)
library(plyr)

# set options for pander
panderOptions('table.split.table', 200)

# set options for knitr
opts_chunk$set(fig.width=5, fig.height=5, cache=FALSE, highlight = TRUE, fig.show="asis")

# load workspace
#load("sensor_mpi_test1_2.RData")

source("../libpurzel/func_plot_moisture.R")
```


### read data table
```{r read data table}
raw_l1 <- read.table("data/sensors_logger1_2011_04_12-2012_12_06.txt", header=T, fill=T)
raw_l2 <- read.table("data/sensors_logger2_2011_05_19-2012_01_18.txt", header=T, fill=T)

# meta information
meta <- read.table("data/sensors_metadata_logger_sensor_channel.txt", header=T)
meta_sub <- droplevels( subset(meta, meta$Study_ID==48656))

# order meta information
meta_sub_ordered <- meta_sub[order(meta_sub$Logger, meta_sub$Kanal_ID),]

# add column for Logger and Kanal ID
meta_sub_ordered <- cbind("variable"=paste("L",meta_sub_ordered$Logger,"_", "K", meta_sub_ordered$Kanal_ID, sep=""), meta_sub_ordered)
meta_sub_ordered2 <- meta_sub_ordered[,c("variable","Treatment", "Cultivar")]

table(meta_sub_ordered2$Cultivar)
```


### convert date
```{r convert date}
raw_l1$Date <- as.Date( as.character(raw_l1$Date_Time), "%d.%m.%y")
raw_l2$Date <- as.Date( as.character(raw_l2$Date_Time), "%d.%m.%y")
```


### subset of raw data (moisture)
```{r subset of raw data}
# subset after 2011-08-15 and before 2011-10-29
l1_sub <- subset(raw_l1, Date > as.Date("2011-08-15") & Date < as.Date("2011-10-29") )
l2_sub <- subset(raw_l2, Date > as.Date("2011-08-15") & Date < as.Date("2011-10-29") )

colnames(l1_sub)
colnames(l2_sub)

# only moisture columns (every second column)
moisture_l1 <- l1_sub[, c(1,74,seq(2, 48, by=2))]
moisture_l2 <- l2_sub[, c(1,122,seq(2, 72, by=2))]

# join l1 and l2 data (without Date/Time)
moisture <- cbind(moisture_l1[,-c(1,2)], moisture_l2[,-c(1,2)])
colnames(moisture) <- paste("L",meta_sub_ordered$Logger,"_", "K", meta_sub_ordered$Kanal_ID, sep="")

# remove 8 columns with values from logger 1
moisture_part <- moisture[, -which(colnames(moisture) %in% c("L1_K7", "L1_K12", "L1_K13", "L1_K14", "L1_K16", "L1_K17", "L1_K19", "L1_K21"))]
```


### format Date_Time
```{r format Date_Time, fig.width=10}
head(l1_sub$Date_Time)

class(l1_sub$Date_Time)
# factor

Date_Time_charac <- as.character(l1_sub$Date_Time)
class(Date_Time_charac)
# character

head(Date_Time_charac)

# strptime: Date-time Conversion Functions to and from Character
Date_Time <- strptime(Date_Time_charac, "%d.%m.%y_%H:%M:%S")
class(Date_Time)
# "POSIXlt" "POSIXt"
head(Date_Time)

# check for missing values
plot(table(as.Date(Date_Time)), las=2)
```


### only data at 12:00
```{r only data at 12:00, fig.width=10}

# return list of moisture values at 12:00
moisture_12_list <- func_plot_moisture_for_hour(hour_value = 12, 
                                                return_table = TRUE,
                                                moisture_values = moisture_part)
# return boxplot
func_plot_moisture_for_hour(hour_value = 12, return_table = FALSE,
                            moisture_values = moisture_part)
```


### only data at 9:00
```{r only data at 9:00, fig.width=10}

# return subset of moisture values at 9:00
moisture_9_list <- func_plot_moisture_for_hour(hour_value = 9, 
                                               return_table = TRUE,
                                               moisture_values = moisture_part)

# return boxplot
func_plot_moisture_for_hour(hour_value = 9, return_table = FALSE,
                            moisture_values = moisture_part)
```


### only data at different timepoints
```{r only data at different timepoints, fig.width=10}
pdf("figures/sensors_moisture_mpi_test_1_2.pdf", width=12, height=8)

for(i in c(0,3,6,9,12,15,18,21) )
  {func_plot_moisture_for_hour(hour_value = i, return_table = FALSE,
                            moisture_values = moisture_part)
  }

dev.off()
```


### only Desiree values at 12:00
```{r only Desiree values at 12:00, fig.width=10}
moisture_12_joined_desiree <- subset(moisture_12_list$sub_joined, 
                                     moisture_12_list$sub_joined$Cultivar=="Desiree")

boxplot(moisture_12_joined_desiree$value ~ moisture_12_joined_desiree$Treatment * moisture_12_joined_desiree$Date,  
        col=c("#4F81BD","#B94441"), xaxt="n", main="Desiree sensors at 12:00", ylim=c(0,600))
axis(1, at = moisture_12_list$xaxis_ticks, labels = moisture_12_list$xaxis_labels, las=2, cex.axis=0.8)


###########################
# return subset of moisture values at 6:00
moisture_6_list <- func_plot_moisture_for_hour(hour_value = 6, 
                                               return_table = TRUE,
                                               moisture_values = moisture_part)

moisture_6_joined_desiree <- subset(moisture_6_list$sub_joined, 
                                     moisture_6_list$sub_joined$Cultivar=="Desiree")

boxplot(moisture_6_joined_desiree$value ~ moisture_6_joined_desiree$Treatment * moisture_6_joined_desiree$Date,  
        col=c("#4F81BD","#B94441"), xaxt="n", main="Desiree sensors at 6:00", ylim=c(0,600))
axis(1, at = moisture_6_list$xaxis_ticks, labels = moisture_6_list$xaxis_labels, las=2, cex.axis=0.8)
```

### save workspace
```{r save workspace}
save.image("sensor_mpi_test_1_2.RData")
```

